const teamName = document.getElementById("team");
const typeOfSport = document.getElementById("sport");
const worldCupYear = document.getElementById("year");
const headCoach = document.getElementById("head-coach");
const playerCards = document.getElementById("player-cards");
const playerDropdownList = document.getElementById("players");
console.log(teamName);
console.log(typeOfSport);
console.log(worldCupYear);
console.log(headCoach);
console.log(playerCards);
console.log(playerDropdownList);
